spring.application.name=kutuphane_otomasyonu
# MySQL Veritabanı Bağlantı Ayarları
# 'kutuphane' adında bir veritabanı (şema) olduğundan emin ol
spring.datasource.url=jdbc:mysql://localhost:3306/kutuphane?createDatabaseIfNotExist=true

# Windows'taki MySQL 'root' kullanıcının şifresi
spring.datasource.username=root
spring.datasource.password=Miya123456

# --- EN ÖNEMLİ SATIR ---
# Spring'e "Java sınıflarıma (Entity) bak ve tabloları OTOMATİK OLUŞTUR" komutu
spring.jpa.hibernate.ddl-auto=update

# (Opsiyonel) Spring'in çalıştırdığı SQL komutlarını terminalde görmek için
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mihracesaliha@gmail.com
spring.mail.password=ebkf yuvt mvvc skqh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

